# Generated by Django 5.0.6 on 2024-05-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ANEA', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
